// Define environmental variables.
#define SCREEN_HEIGHT 				127
#define SCREEN_WIDTH 				127
#define SCREEN_CENTER				63

#define RACKET_THICKNESS 			6
#define RACKET_LENGTH 				48

#define RACKET_LEFT_PERIOD 			99
#define RACKET_LEFT_LIMIT_X_LEFT 	RACKET_THICKNESS/2 // 3
#define RACKET_LEFT_LIMIT_X_RIGHT 	RACKET_THICKNESS + RACKET_THICKNESS/2 // 9
#define RACKET_LEFT_LIMIT_Y_DOWN	SCREEN_HEIGHT - RACKET_LENGTH/2 // 103
#define RACKET_LEFT_LIMIT_Y_UP	 	RACKET_LENGTH/2 // 24
#define RACKET_LEFT_POS_X			(RACKET_LEFT_LIMIT_X_LEFT + RACKET_LEFT_LIMIT_X_RIGHT)/2
#define RACKET_LEFT_POS_Y			SCREEN_CENTER - 1 // 62
//
#define RACKET_RIGHT_PERIOD 		100
#define RACKET_RIGHT_LIMIT_X_LEFT 	SCREEN_WIDTH - (RACKET_THICKNESS + RACKET_THICKNESS/2) //118
#define RACKET_RIGHT_LIMIT_X_RIGHT 	SCREEN_WIDTH - RACKET_THICKNESS/2 // 124
#define RACKET_RIGHT_LIMIT_Y_DOWN 	SCREEN_HEIGHT - RACKET_LENGTH/2 // 103
#define RACKET_RIGHT_LIMIT_Y_UP 	RACKET_LENGTH/2 // 24
#define RACKET_RIGHT_POS_X			(RACKET_RIGHT_LIMIT_X_LEFT + RACKET_RIGHT_LIMIT_X_RIGHT)/2 // 121
#define RACKET_RIGHT_POS_Y			SCREEN_CENTER // 63
//
//
#define BALL_PERIOD					30
#define BALL_THICKNESS 				RACKET_THICKNESS // 6
#define BALL_LIMIT_X_RIGHT			RACKET_RIGHT_LIMIT_X_LEFT - BALL_THICKNESS/2 // 115
#define BALL_LIMIT_X_LEFT			RACKET_LEFT_LIMIT_X_RIGHT + BALL_THICKNESS/2 // 12
#define BALL_LIMIT_Y_UP				BALL_THICKNESS/2 // 3
#define BALL_LIMIT_Y_DOWN			SCREEN_HEIGHT - BALL_THICKNESS/2 // 124
#define BALL_INIT_LEFT_POS_X		RACKET_LEFT_LIMIT_X_RIGHT + BALL_THICKNESS/2 + 1 // 13
#define BALL_INIT_LEFT_POS_Y		RACKET_LEFT_POS_Y // 62
#define BALL_INIT_RIGHT_POS_X		RACKET_RIGHT_LIMIT_X_LEFT - BALL_THICKNESS/2 - 1 // 114
#define BALL_INIT_RIGHT_POS_Y		RACKET_RIGHT_POS_Y // 63
//

#define RACKET_Y_RANGE 				RACKET_LENGTH/2 + RACKET_THICKNESS/2


#define SCORE_POS_P1_X				SCREEN_CENTER/2
#define SCORE_POS_P1_Y				2*BALL_THICKNESS

#define SCORE_POS_P2_X				SCREEN_CENTER + SCREEN_CENTER/2
#define SCORE_POS_P2_Y				2*BALL_THICKNESS

//
#define WINNER_SCORE				2


#define LOGIC_PERIOD				30

#define NO_HIT						0
#define HIT_LEFT_RACKET  			1
#define HIT_LEFT_WALL	  			2
#define HIT_RIGHT_RACKET  			3
#define HIT_RIGHT_WALL	  			4
#define HIT_TOP_WALL  				5
#define HIT_BOTTOM_WALL	  			6

#define P1_WON_POS_X				BALL_LIMIT_X_RIGHT - RACKET_LENGTH/2 //114
#define P1_WON_POS_Y				SCREEN_CENTER

#define P2_WON_POS_X				BALL_LIMIT_X_LEFT + RACKET_LENGTH/2 //13
#define P2_WON_POS_Y				SCREEN_CENTER


#define PLAYER_1_WON_SCREEN				1
#define PLAYER_2_WON_SCREEN				2
#define NO_WINNER_YET					3

#define GAME_RUNNING_SCREEN				3
#define WINNER_SCREEN					4
#define GAME_INIT_SCREEN				5


#define GAME_RUNNING_STATE				1
#define WINNER_STATE_RACKET_LEFT		2
#define WINNER_STATE_RACKET_RIGHT		3
#define GAME_INIT_STATE					4

#define INIT_WINNER_SCREEN_COUNTER		0
#define FINAL_WINNER_SCREEN_COUNTER		200
