// Define enviromental variables.
#define RACKET_THICKNESS			3

#define RACKET_LEFT_PERIOD 			100

#define RACKET_LEFT_LIMIT_X_LEFT 	4
#define RACKET_LEFT_LIMIT_X_RIGHT 	8

#define RACKET_LEFT_LIMIT_Y_UP 		103
#define RACKET_LEFT_LIMIT_Y_DOWN 	24
#define RACKET_LEFT_POS_X			120
#define RACKET_LEFT_POS_Y			63
//
#define RACKET_RIGHT_PERIOD 		100

#define RACKET_RIGHT_LIMIT_X_LEFT 	120
#define RACKET_RIGHT_LIMIT_X_RIGHT 	124

#define RACKET_RIGHT_LIMIT_Y_UP 	103
#define RACKET_RIGHT_LIMIT_Y_DOWN 	24
#define RACKET_RIGHT_POS_X			120
#define RACKET_RIGHT_POS_Y			63
//
//
#define BALL_PERIOD					100
#define BALL_INIT_POS_X				RACKET_LEFT_POS_X+RACKET_THICKNESS
#define BALL_INIT_POS_Y				63
#define BALL_LIMIT_X_LEFT			6
#define BALL_LIMIT_X_RIGHT			122
#define BALL_LIMIT_Y_UP				124
#define BALL_LIMIT_Y_DOWN			3

